services:
  java_app:
    container_name: java_app
    image: catalogo-libros-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://java_db:5432/catalogodelibros
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
    stdin_open: true
    tty: true
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: catalogodelibros
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
