version: "3.9"

services:
  java_app:
    container_name: java_app
    image: catalogo-libros-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://java_db:5432/postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
